name: Build and deploy ASP.NET Core to Azure Web App

on:
  push:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  PROJECT_FILE: 'Library App/Library App.csproj'
  PUBLISH_DIR: '${{ github.workspace }}/publish'
  AZURE_WEBAPP_NAME: 'libraryapp-guhjcucmd2bwdpg8'
  DOTNET_VERSION: '9.0.x'

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Restore
        run: dotnet restore "${{ env.PROJECT_FILE }}"

      - name: Build
        run: dotnet build "${{ env.PROJECT_FILE }}" --configuration Release --no-restore

      - name: Publish
        run: dotnet publish "${{ env.PROJECT_FILE }}" -c Release -o "${{ env.PUBLISH_DIR }}" --no-restore

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: app
          path: ${{ env.PUBLISH_DIR }}

  deploy:
    runs-on: windows-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: app
          path: app_publish

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0C2F1A0E75EA4AD3BEEDDE61AC20E784 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_1CFB424CB53A4F7CB8ADEBC8990F1126 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_40CE25BCA95540CF902CF5E77DF8A725 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.AZURE_WEBAPP_NAME }}
          package: app_publish
